config/routes.rb
Educare::Application.routes.draw do
  

  resources :teachers do
    resources :students
  end

  resources :messages
  resources :articles

  get "academic_group_first" => "teachers#academic_group_first"
  get "academic_group_second" => "teachers#academic_group_second"
  get "academic_group_third" => "teachers#academic_group_third"
  root "pages#home"
  get "about" => "pages#about"

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :teachers
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_many :students
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "20x20>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article , only: [:show, :edit, :update, :destroy]


	def index
		@articles = Article.all.order("created_at DESC")
	end

	def show
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		if(@article.save)
			redirect_to articles_path
		else
			render :new
		end

	end

	def edit
	end

	def update
		if(@article.update(article_params))
			redirect_to articles_path
		else
			render :edit
		end
	end

	def destroy
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title , :content , :image)
		end



end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_message, only:[:show,:edit,:update,:destroy]
	


	def index
	end

	def show
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)

		if(@message.save)
			flash[:notice] = "謝謝您～您的需求與意見我們已經收到囉！"
			redirect_to about_path
		else
			flash[:notice] = "不好意思，您似乎有資料漏填囉~"
			render :new
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private
		def set_message
			@message = Message.find(params[:id])
		end

		def message_params
			params.require(:message).permit(:name , :mail , :content)
		end
			


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@teachers = Teacher.where(:academic_group => 1).order("created_at Desc")

	end

	def about
	end
	
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :find_teachers

	def index
	end

	def show
	end

	def new
		@student = @teacher.students.build
	end


	def create
		@student = @teacher.students.new(student_params)

		if(@student.save)
			flash[:notice] = "感謝您留下資料，待我們與老師聯絡後會盡快通知您，謝謝！"
			redirect_to(teachers_path)
		else
			render :new
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end


	private
		def find_teachers
			@teacher = Teacher.find(params[:teacher_id])
		end

		def student_params
			params.require(:student).permit(:name , :mail , :phoneNumbers , :message)
		end


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	before_action :set_teacher, only:[:show,:edit,:update,:destroy]

	def index
		@teachers = Teacher.all.order("created_at DESC")
	end

	def academic_group_first
		@teachers = Teacher.where(:academic_group => 1).order("created_at DESC")
		#@north_teachers = Teacher.where(:academic_group => 1 , :location => 1).order("created_at DESC")
		#@hsinchu_teachers = Teacher.where(:academic_group => 1, :location => 2).order("created_at DESC")
		#@south_teachers = Teacher.where(:academic_group => 1, :location => 3).order("created_at DESC")
	end

	def academic_group_second
		@north_teachers = Teacher.where(:academic_group => 2, :location => 1).order("created_at DESC")
		@hsinchu_teachers = Teacher.where(:academic_group => 2,:location => 2).order("created_at DESC")
		@south_teachers = Teacher.where(:academic_group => 2, :location => 3).order("created_at DESC")
	end

	def academic_group_third
		@north_teachers = Teacher.where(:academic_group => 3, :location => 1).order("created_at DESC")
		@hsinchu_teachers = Teacher.where(:academic_group => 3, :location => 2).order("created_at DESC")
		@south_teachers = Teacher.where(:academic_group => 3, :location => 3).order("created_at DESC")
	end

	def show
	end

	def new
		@teacher = Teacher.new
	end

	def create
		@teacher = Teacher.new(teacher_params)

		if(@teacher.save)
			redirect_to(@teacher, notice: 'teacher was successfully created')
		else
			format.html {render action: 'new'}
		end

	end

	def edit
	end

	def update
		if(@teacher.update(teacher_params))
			redirect_to teachers_path
		else
			render action: 'edit'
		end
	end

	def destroy
		if(@teacher.present?)
			@teacher.destroy
			redirect_to teachers_path
		end
	end


	private
		# Use callbacks to share common setup or constraints between actions.
		def set_teacher
			@teacher = Teacher.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def teacher_params
			params.require(:teacher).permit(:name , :image , :expertise , :background, :academic_group, :location ,:introduction)
		end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/articles/_form.html.erb
<div class="well">

<%= form_for @article ,:html => {:multipart=> true}  do |f|%>
	<% if(@article.errors.any?) %>
		<div id="error_explanation">
			<h2><% pluralized(@article.error.count , "error") %>
				prohibited this message being saved:<h2>

			<ul>
				<%= @article.errors.full_message.each do |msg|%>
					<li><%= msg%><li>
				<% end %>
			</ul>
		</div>
	<% end %>


	<div class="form-group">
		<%= f.label(:title, 'title') %>
		<%= f.text_field(:title, class: "form-control") %>

		
	</div>

	<div class = "form-group">
		<%= f.label(:content, "content")%>
		<%= f.text_area(:content, class: "form-control" , rows: '8') %>
	
	</div>

	<div class= "form-group">
		<%= f.label(:image, "image")%>
		<%= f.file_field(:image , class: "form-control")%>
	</div>

	<div class="form-group">
		<%= f.submit(class: 'btn btn-primary') %>
	</div>



<%end%>


</div>

app/views/articles/edit.html.erb
<h1> edit article</h1>

<%= render 'form'%>

<%= link_to('back', articles_path)%>

<h1> New Teacher</h1>
<%= render 'form'%>

<%= link_to('Back' , teachers_path)%>

app/views/articles/index.html.erb
<% @articles.each do |article|%>
	

<div class="content">

<div class="post container">
	<div class = row>
		<div class="col-md-12">
		<h2><strong><%= article.title %></strong></h2>
		</div>
	</div>

	<br>
		
	<div class="row">
	
		<div class="col-md-4">
			<%= image_tag(article.image.url(:medium), class: "img-rounded img-article") %>
		</div>
		<div class="col-md-8">
			<h4><%= simple_format(article.content) %></h4>
		</div>


	</div>

	<!--<hr class="style-four">-->
</div>

</div>

<%end%>

app/views/articles/new.html.erb
<h1> new article</h1>

<%= render 'form'%>

<%= link_to('back', articles_path)%>

app/views/layouts/_header.html.erb
<!--
<nav class="navbar navbar-inverse navbar-default" role="navigation">
-->
  <!-- Brand and toggle get grouped for better mobile display -->
<!--
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">
      <p class="logo">eduCare</p>
      推甄申請諮詢平台
    </a>
    
  </div>
-->
  <!-- Collect the nav links, forms, and other content for toggling -->
<!--
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "咨詢團隊", root_path %></li>
      <li><%= link_to "面試＆備審準備技巧", about_path %></li>
      <li><%= link_to "Q&A", about_path %></li>
      <li><%= link_to "關於Educare", about_path %></li>
     
    </ul>
-->
<!--
  </div>
-->
  <!-- /.navbar-collapse -->



<!--
</nav>
-->



<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header col-md-6">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <div class="col-md-4">
      <%=link_to(root_path, class: 'navbar-brand')  do%>
      <%=image_tag('big-logo.png', class: 'logo' )%>
        
        <!--<img class="logo" src="https://dl.dropboxusercontent.com/u/256084506/logo2.png"></img>-->
      <%end %>
    </div>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "首頁", root_path  %></li>
      <li><%= link_to "教師平台", academic_group_first_path  %></li>
      <li><%= link_to "面試＆備審準備技巧", articles_path %></li>
      <li><%= link_to "Q&A", about_path %></li>
      <li><%= link_to "聯絡我們", about_path%></li>
      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/messages/_form.html.erb
<div class="well">
<%= form_for(@message) do |f| %>
	
	<% if(@message.errors.any?) %>
		<div id="error_explanation">
			<h2><%= pluralized(@message.error.count , "error") %> prohibited this messge being saved:</h2>
			<ul>
				<%= message.errors.full_message.each do |msg|%>
					<li><%= msg%></li>
				<% end %>
			</ul>

		</div>
	<%end%>

	<div class="form-group">
		<%=f.label(:name, '稱呼:')%>
		<%=f.text_field(:name , class: "form-control")%>
	</div>


	<div class="form-group">
		<%=f.label(:mail, 'Emal:')%>
		<%=f.text_field(:mail , class: "form-control")%>
	</div>


	<div class="form-group">
		<%=f.label(:content , "對Educare想說的話:")%>
		<%=f.text_area(:content , class: "form-control", rows: "8") %>
	</div>

	 <div class="form-group">
    <%= f.submit("送出資料" ,class: "btn btn-primary") %>
  </div>


<%end%>
</div>

app/views/messages/new.html.erb
<div class="well">
	<h4>親愛的家長您好，請在以下表格中填入您的需求以及意見，eduCare團隊在收到訊息後會儘速與您聯絡並改進服務，謝謝！</h4>
</div>
<%= render 'form'%>

<%= link_to('Back' , root_path)%>

app/views/pages/about.html.erb
<script type="text/javascript">
	mixpanel.track(
	    'about'
	);
</script>



<div class="content">
<div class="post container">

		<div class="row">
			
			<div class = "col-md-12 well center">
				
				<%=link_to( '聯絡eduCare' ,new_message_path, class: 'btn btn-primary btn-lg')%>
			</div>


			<div class="col-md-6">
				<%=image_tag( 'dm.jpg' , class: 'dm')%>

			</div>

			<div class="col-md-6">
				<p>eduCare是一個提供大學申請入學咨詢的平台。從申請入學到錄取知名大學校系，我們提供全程一對一指導，協助學生了解大學科系，協助備審資料與面試技巧準備。 我們協助申請入學的考生能夠找到合適的咨詢老師，咨詢老師來自於台大、清大、交大、政大等頂尖大學，本身具備與申請科系相符合的專業知識，協助考生在面試時遇到的科系知識問題。我們更挑選本身已有推甄申請經驗以及有咨詢經驗的老師提供考生最棒的咨詢服務。</p>

				<span class="glyphicon glyphicon-envelope contact"></span> service@educare.tw  
				<span class="glyphicon glyphicon-earphone contact"></span> 0937-402634
			</div>
		</div>
</div>
</div>

app/views/pages/home.html.erb
<script type="text/javascript">
	mixpanel.track(
	    'home'
	);
</script>



<div class="content">
<div class="post container">

		<!--<h2 class="center">Educare大學申請入學諮詢平台</h2>
		<h4 class="center">school adminission consulting</h4>-->
		<div class="center">
			<span class="gray">Educare</span>
			<span class="blue">大學申請入學諮詢平台</span>
			<div class="description">school adminission consulting</div>
		</div>


		<div class="btn-group btn-group-justified">
		 
		  <a id="button-img-1" class="btn btn-default btn-lg active">諮詢服務流程</a>
		  <a  id="button-img-2" class="btn btn-default btn-lg">為何選擇Educare</a>
		  <a id="button-img-3" class="btn btn-default btn-lg">Educare貼心小禮物</a>
		</div>

		<%=link_to(new_message_path) do%>
		<%=image_tag( 'poster1.png' , class: 'dm', id: 'introduction-img')%>
		<%end%>
		<!--<div class="jumbotron">-->
		    <!--
		    <h1>eduCare</h1>
		    <h2>大學申請入學咨詢平台(C2C School Admissions Consulting)</h2>
		    <p>eduCare是一個提供大學申請入學咨詢的平台。從申請入學到錄取知名大學校系，我們提供全程一對一指導，協助學生了解大學科系，協助備審資料與面試技巧準備。 我們協助申請入學的考生能夠找到合適的咨詢老師，咨詢老師來自於台大、清大、交大、政大等頂尖大學，本身具備與申請科系相符合的專業知識，協助考生在面試時遇到的科系知識問題。我們更挑選本身已有推甄申請經驗以及有咨詢經驗的老師提供考生最棒的咨詢服務。</p>
				-->
				<!--
				<%=image_tag( 'https://dl.dropboxusercontent.com/u/256084506/dm.jpg' , class: 'dm')%>
				-->
			
		 <!--</div>-->


</div>
</div>

<div class="content">
<div class="post container">

		<h1>咨詢團隊</h1>



		<ul class="nav nav-tabs nav-justified">
		  <li class="active"><%= link_to( '第一類組' , academic_group_first_path)%></li>
		  <li><%= link_to( '第二類組' , academic_group_second_path)%></li>
		  <li><%= link_to( '第三類組' , academic_group_third_path)%></li>
		</ul>


		</br>

		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>台/新北市</strong></h4>
			</div>

			<% @teachers.where(:location => 1).each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>


				</div><!-- col-md-4 -->
			<%end%>
		</div>



		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>新竹縣/市</strong></h4>
			</div>

			<% @teachers.where(:location => 2).each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>


		<div class="row">
			<div class="alert text-center alert-success">
		  <h4><strong>台南/高雄</strong></h4>
			</div>

			<% @teachers.where(:location => 3).each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>
</div>
</div>

app/views/teachers/academic_group_first.html.erb
<script type="text/javascript">
	mixpanel.track(
	    'academic_group_first'
	);
</script>

<div class="content">
<div class="post container">

		<h1>諮詢團隊</h1>


		<ul class="nav nav-tabs nav-justified">
		  <li class="active"><%= link_to( '第一類組' , academic_group_first_path)%></li>
		  <li><%= link_to( '第二類組' , academic_group_second_path)%></li>
		  <li><%= link_to( '第三類組' , academic_group_third_path)%></li>
		</ul>


		</br>

		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>台/新北市</strong></h4>
			</div>

			<% @teachers.where(:location => 1).each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>


				</div><!-- col-md-4 -->
			<%end%>
		</div>

</div>
</div>



<div class="content">
<div class="post container">

		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>新竹縣/市</strong></h4>
			</div>

			<% @teachers.where(:location => 2).each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>

</div>
</div>



<div class="content">
<div class="post container">

		<div class="row">
			<div class="alert text-center alert-success">
		  <h4><strong>台南/高雄</strong></h4>
			</div>

			<% @teachers.where(:location => 3).each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>

</div>
</div>

app/views/teachers/academic_group_second.html.erb
<div class="content">
<div class="post container">

		<h1>諮詢團隊</h1>



		<ul class="nav nav-tabs nav-justified">
		  <li><%= link_to( '第一類組' , academic_group_first_path)%></li>
		  <li class="active"><%= link_to( '第二類組' , academic_group_second_path)%></li>
		  <li><%= link_to( '第三類組' , academic_group_third_path)%></li>
		</ul>


		</br>

		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>台/新北市</strong></h4>
			</div>

			<% @north_teachers.each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>
		</div>

</div>
</div>



<div class="content">
<div class="post container">

		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>新竹縣/市</strong></h4>
			</div>

			<% @hsinchu_teachers.each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>

</div>
</div>


<div class="content">
<div class="post container">

		<div class="row">
			<div class="alert text-center alert-success">
		  <h4><strong>台南/高雄</strong></h4>
			</div>

			<% @south_teachers.each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>
						
					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>

</div>
</div>

app/views/teachers/academic_group_third.html.erb
<div class="content">
<div class="post container">
		<h1>諮詢團隊</h1>



		<ul class="nav nav-tabs nav-justified">
		  <li><%= link_to( '第一類組' , academic_group_first_path)%></li>
		  <li><%= link_to( '第二類組' , academic_group_second_path)%></li>
		  <li class="active"><%= link_to( '第三類組' , academic_group_third_path)%></li>
		</ul>


		</br>

		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>台/新北市</strong></h4>
			</div>

			<% @north_teachers.each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>
		</div>
</div>
</div>


<div class="content">
<div class="post container">


		<div class="row">

			<div class="alert text-center alert-success">
		  <h4><strong>新竹縣/市</strong></h4>
			</div>

			<% @hsinchu_teachers.each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>

					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>

</div>
</div>


<div class="content">
<div class="post container">

		<div class="row">
			<div class="alert text-center alert-success">
		  <h4><strong>台南/高雄</strong></h4>
			</div>

			<% @south_teachers.each do |teacher| %>

				<div class="col-md-3">
					
					<div class="col-md-12 panel panel-default">
					  
					  <div class="panel-heading center">
					  	<%= teacher.background %></br>
					  	<%= teacher.name %>
					  </div>

					  <div class="panel-body">
					    <%= image_tag(teacher.image.url(:medium), class: "img-avatar img-rounded") %>
					  </div>
					
						<div class="panel-footer">
							教學內容：</br>
							<%= simple_format(teacher.expertise) %>
							<div class="center">
								<%= link_to('聯絡老師', new_teacher_student_path(teacher) , :class => "btn btn-primary" )%>
							</div>
						</div>
						
					</div>
				</div><!-- col-md-4 -->
			<%end%>

		</div>
</div>
</div>